<a href="https://colab.research.google.com/github/memari-majid/convolutional-neural-network/blob/main/ConvNet_implement_001.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 2D ConvNet
Naive Convolution Implementation

In [ ]:
import cv2 
import numpy as np

In [ ]:
# mount google drive
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


### Pre-processing  
* Grayscale image = 2-d Conv
* When reading images with **OpenCV**, the default mode is **BGR** and not **RGB**, so we will specify the code parameter as BGR2GRAY, allowing us to turn the BGR image into a grayscaled image. 

In [ ]:
# reading image
image = cv2.imread('/content/drive/MyDrive/Notebooks/Coding/image.jpeg') 
print(f'image shape RGB = {image.shape}')
# converting BGR to Graysclae
image = cv2.cvtColor(src=image, code=cv2.COLOR_BGR2GRAY) 
print(f'image shape Grayscale = {image.shape}')

image shape RGB = (359, 638, 3)
image shape Grayscale = (359, 638)


In [ ]:
# Edge Detection Kernel
kernel = np.array([[-1, -1, -1], 
                   [-1, 8, -1], 
                   [-1, -1, -1]])
print(kernel)

[[-1 -1 -1]
 [-1  8 -1]
 [-1 -1 -1]]


* CV2 uses Cross Correlation = flipped Convolution 
* Need to **flipp** the matrix horizontally then vertically

In [ ]:
# flipped Cross Correlation = Convolution
kernel = np.flipud(np.fliplr(kernel))
print(kernel)

[[-1 -1 -1]
 [-1  8 -1]
 [-1 -1 -1]]


In [ ]:
# Input Shape
xImgShape = image.shape[0]
yImgShape = image.shape[1]

In [ ]:
# Kernel Shape
xKernShape = kernel.shape[0]
yKernShape = kernel.shape[1]

In [ ]:
# Padding Size
padding = 2
# Default Strides Size
strides = 1

We multiply the padding by 2 because we are applying even padding on all sides so a padding of 1 would increase the dimension of the padded image by 2.


In [ ]:
# Conv Output Shape
xOutput = int(((xImgShape - xKernShape + 2 * padding) / strides) + 1)
yOutput = int(((yImgShape - yKernShape + 2 * padding) / strides) + 1)
output = np.zeros((xOutput, yOutput))
print(f' output shape = {output.shape}')

 output shape = (361, 640)


In [ ]:
# Apply Equal Padding to All Sides
if padding != 0:
    # adding 2 padding to X and Y
    imagePadded = np.zeros((image.shape[0] + padding*2, image.shape[1] + padding*2))
    # replacing the inner portion of the padded image with the image
    # nd array slicing [padding:-padding] = [1:-1]
    imagePadded[int(padding):int(-1 * padding), int(padding):int(-1 * padding)] = image
    print(f'Padded Image Shape = {imagePadded.shape}')
    print(imagePadded)
else:
    imagePadded = image

Padded Image Shape = (363, 642)
[[ 0.  0.  0. ...  0.  0.  0.]
 [ 0.  0.  0. ...  0.  0.  0.]
 [ 0.  0. 78. ... 44.  0.  0.]
 ...
 [ 0.  0. 40. ... 17.  0.  0.]
 [ 0.  0.  0. ...  0.  0.  0.]
 [ 0.  0.  0. ...  0.  0.  0.]]


### Convolution 
* iterate through the image 
* element wise multiplication
* sum

In [ ]:
# Iterate through columns
for y in range(image.shape[1]):
    # stop when y out of kernel size
    if y > image.shape[1] - yKernShape:
        break
    # Y must be divisble by strides
    if y % strides == 0:
        for x in range(image.shape[0]):
            # stop when x out of kernel size
            if x > image.shape[0] - xKernShape:
                break
            try:
                # X must be divisble by strides
                if x % strides == 0:
                  # slicing[x:kernel size] slicing[y:kernel size]
                  output[x, y] = (kernel * imagePadded[x: x + xKernShape, y: y + yKernShape]).sum()
            except:
                break

In [ ]:
cv2.imwrite('2DConvolved.jpg', output)
'2DConvolved.jpg'

'2DConvolved.jpg'